### PR TITLE
debug_build.sh: initial commit

### PR DESCRIPTION
**Pull request by junghans**
Fix https://github.com/votca/votca/issues/51

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
OMG, this is awesome!!!

**Review by junghans — COMMENTED** [review]
I think, we should add a clean up option for the temp directory and the local docker container!

And I guess the local container tag is hard coded to `votca_debug` I will add an option for that!

And maybe unzip the artifacts quietly!

**Review by JensWehner — COMMENTED** [review]
Okay what do I have to do to run it?

**Comment by junghans** [comment]
```
./debug_build.sh xtp ./artifacts.zip
```

**Comment by junghans** [comment]
Give it some testing and then merge!

**Comment by junghans** [comment]
ping @JensWehner

**Comment by junghans** [comment]
ping @JoshuaSBrown @JensWehner

**Review by JoshuaSBrown — DISMISSED** [review]

**Review by JensWehner — DISMISSED** [review]
Great contribution

**Review by JensWehner — APPROVED** [review]
very nice

**Pull request merged**
